package com.people.entities;
// Generated 20-ago-2020 18:17:28 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Course generated by hbm2java
 */
@Entity
@Table(name = "course", schema = "public")
public class Course implements java.io.Serializable {

	private Integer idCourse;
	private String name;
	private String code;
	private Set<Student> students = new HashSet<Student>(0);

	public Course() {
	}

	public Course(String code) {
		this.code = code;
	}

	public Course(String name, String code, Set<Student> students) {
		this.name = name;
		this.code = code;
		this.students = students;
	}

	@SequenceGenerator(name = "com.people.entities.CourseIdGenerator", sequenceName = "course_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "com.people.entities.CourseIdGenerator")

	@Column(name = "id_course", unique = true, nullable = false)
	public Integer getIdCourse() {
		return this.idCourse;
	}

	public void setIdCourse(Integer idCourse) {
		this.idCourse = idCourse;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "code", nullable = false, length = 4)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "course")
	public Set<Student> getStudents() {
		return this.students;
	}

	public void setStudents(Set<Student> students) {
		this.students = students;
	}

}
