package com.people.entities;
// Generated 20-ago-2020 18:17:28 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Student generated by hbm2java
 */
@Entity
@Table(name = "student", schema = "public")
public class Student implements java.io.Serializable {

	private Integer idStudent;
	private Course course;
	private String rut;
	private String name;
	private String lastname;
	private Integer age;

	public Student() {
	}

	public Student(Course course, String name, String lastname) {
		this.course = course;
		this.name = name;
		this.lastname = lastname;
	}

	public Student(Course course, String rut, String name, String lastname, Integer age) {
		this.course = course;
		this.rut = rut;
		this.name = name;
		this.lastname = lastname;
		this.age = age;
	}

	@SequenceGenerator(name = "com.people.entities.StudentIdGenerator", sequenceName = "student_seq", initialValue = 1, allocationSize = 1)
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator = "com.people.entities.StudentIdGenerator")

	@Column(name = "id_student", unique = true, nullable = false)
	public Integer getIdStudent() {
		return this.idStudent;
	}

	public void setIdStudent(Integer idStudent) {
		this.idStudent = idStudent;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_course", nullable = false)
	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	@Column(name = "rut", length = 15)
	public String getRut() {
		return this.rut;
	}

	public void setRut(String rut) {
		this.rut = rut;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "lastname", nullable = false, length = 50)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "age")
	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

}
